run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
    - unparam

linters-settings:
  errcheck:
    check-blank: true
  goimports:
    local-prefixes: github.com/konflux-ci/release-service

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
