repos:
  - repo: https://github.com/jorisroovers/gitlint
    rev: acc9d9de6369b76d22cb4167029d2035e8730b98 # v0.19.1
    hooks:
      - id: gitlint
        stages: [commit-msg]

  - repo: https://github.com/dnephin/pre-commit-golang
    rev: fb24a639f7c938759fe56eeebbb7713b69d60494 # v0.5.1
    hooks:
      - id: go-fmt
        args: ['-s']
        files: '\.go$'
