# Documentation: https://docs.codecov.io/docs/codecov-yaml
codecov:
  require_ci_to_pass: false

ignore:
  - "api/v1alpha1/zz_generated.deepcopy.go" # generated file
  - "e2e-tests/**"

coverage:
  status:
    # Allows coverage to drop by 1% when compared against the base commit.
    project:
      default:
        target: auto
        threshold: 1%
        informational: true
    # Sets the expected status for `codecov/patch` check.
    # We set this to be only informational hence it does not cause the check to fail.
    patch:
      default:
        target: 80%
        informational: true

comment:
  layout: "reach,diff,flags,files,footer"
  require_changes: true
