---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: prevent-all-egress
  namespace: system
spec:
  podSelector:
    matchLabels:
      control-plane: controller-manager
  policyTypes:
    - Egress
  egress:
    - to:
        - ipBlock:
            cidr: 172.30.0.0/24
