---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: prevent-all-egress-allow-api-server
  namespace: system
spec:
  podSelector:
    matchLabels:
      control-plane: controller-man
  policyTypes:
    - Egress
  egress:
    - to:
        - ipBlock:
            cidr: 172.30.0.0/24
      ports:
        - protocol: TCP
          port: 443
        - protocol: TCP
          port: 6443     
    - to:
        - ipBlock:
            cidr: 10.128.2.0/24
      ports:
        - protocol: TCP
          port: 443
        - protocol: TCP
          port: 80               