---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-https-only-for-specific-ports-ingress
  namespace: system
spec:
  podSelector:
    matchLabels:
      control-plane: controller-manager
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - matchExpressions:
    - key: port
      operator: In
      values:
      - "443"
      - "444"
      - "4443"
      - "8080"
      - "8081"
      - "8443"
      - "9443"
    - key: scheme
      operator: In
      values:
      - https
  egress: []
