---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: egress-block-all
  namespace: system
spec:
  podSelector:
    matchLabels:
      control-plane: controller-manager
  policyTypes:
    - Egress  