---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-egress-to-api-server-dns-and-kubelet
  namespace: system
spec:
  podSelector:
    matchLabels:
      control-plane: controller-manager
  policyTypes:
    - Egress
  egress:
    - to:
      - namespaceSelector:
          matchLabels:
            name: kube-system
        podSelector:
          matchLabels:
            k8s-app: kube-apiserver-proxy
      ports:
      - name: https
        port: 443
        protocol: TCP  
      - port: 10250     
        protocol: TCP  
      - port: 10255     
        protocol: TCP   
      - port: 4194     
        protocol: TCP   

    - to:
      - namespaceSelector:
          matchLabels:
            name: openshift-dns             
      ports:
        - port: 53     
          protocol: TCP                                              
        - port: 9154
          protocol: TCP                   
        - port: 53     
          protocol: UDP                   
