{
 "title": "Release Service",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Total releases",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum by (namespace) (release_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Successful releases",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum by (namespace) (release_total{release_reason=\"Succeeded\"}) / sum by (namespace) (release_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Concurrent releases",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (namespace) (release_concurrent_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time to succeed",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 9, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum by (namespace, release_reason, le) (release_duration_seconds_bucket{release_reason=\"Succeeded\"})",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Total number of reconciles by type",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "sum(controller_runtime_reconcile_total{controller=\"release\",result=\"error\"})",
     "legendFormat": "Error"
    },
    {
     "expr": "sum(controller_runtime_reconcile_total{controller=\"release\",result=\"requeue\"})",
     "legendFormat": "Requeue"
    },
    {
     "expr": "sum(controller_runtime_reconcile_total{controller=\"release\",result=\"requeue_after\"})",
     "legendFormat": "Requeue after"
    },
    {
     "expr": "sum(controller_runtime_reconcile_total{controller=\"release\",result=\"success\"})",
     "legendFormat": "Success"
    }
   ]
  },
  {
   "title": "Failed releases",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum by (namespace) (release_total{release_reason=\"Failed\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Invalid releases",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum by (namespace) (release_total{validation_reason=\"Failed\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Releases",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum by (namespace, release_reason) (rate(release_total{release_reason=~\"Failed|Succeeded\"}[$__rate_interval]))",
     "legendFormat": "{{release_reason}}"
    }
   ]
  },
  {
   "title": "Time to fail",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 9, "x": 9, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum by(namespace, release_reason, le) (release_duration_seconds_bucket{release_reason=\"Failed\"})",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Workqueue retries",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
   "targets": [
    {
     "expr": "sum(workqueue_retries_total{name=\"release\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Retry mitigations",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(release_retry_mitigation_success_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Retry mitigations by failure",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum by (failure_reason, task, step) (release_retry_mitigation_success_total)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}