{
 "title": "Release Attempts",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Total number of releases",
   "type": "stat",
   "description": "Total number of releases processed by the operator",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "release_attempt_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total number failed releases",
   "type": "stat",
   "description": "Total number of releases processed by the operator",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "release_attempt_total{succeeded=\"false\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Concurrent requests",
   "type": "stat",
   "description": "Total number of concurrent release attempts",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(release_attempt_concurrent_requests)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Percentage of successful releases",
   "type": "stat",
   "description": "Total number of releases processed by the operator",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "release_attempt_total{succeeded=\"true\"} / release_attempt_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total number failed releases",
   "type": "stat",
   "description": "Total number of releases processed by the operator",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "release_attempt_invalid_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Time to complete releases",
   "type": "bargauge",
   "description": "Release durations from the moment the release resource was created til the release is marked as running",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "release_attempt_duration_seconds_bucket",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Time to start running releases",
   "type": "bargauge",
   "description": "Release durations from the moment the release resource was created til the release is marked as running",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "release_attempt_running_seconds_bucket",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}