---
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: simple-e2e-pipeline
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: release
spec:
  description: >-
    Minimal pipeline used for tenant E2E testing. It contains a single task
    that echo output.
  params:
    - name: release
      type: string
    - name: releasePlan
      type: string
    - name: snapshot
      type: string
  tasks:
    - name: task-01
      taskSpec:
        steps:
          - name: task-01-step-01
            image: quay.io/konflux-ci/release-service-utils@sha256:850118bc6eda4ca3f98ef1e53109164f64a0945a6ac0942f908b7e106f50775c
            computeResources:
              requests:
                memory: 32Mi
                cpu: 50m
              limits:
                memory: 32Mi
            script: |
              #!/usr/bin/env bash
              echo "simple-e2e-pipeline: complete"
