# permissions for end users to view releaseplans.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: releaseplan-viewer-role
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: 'true'
rules:
- apiGroups:
  - appstudio.redhat.com
  resources:
  - releaseplans
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - appstudio.redhat.com
  resources:
  - releaseplans/status
  verbs:
  - get
