{
 "title": "Release Service breakdown dashboard",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(release_total,source_cluster)"
    }
   },
   {
    "name": "tenant",
    "label": "managed tenant",
    "query": {
     "query": "label_values(release_total,target)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 18, "x": 0, "y": 0 },
   "options": {
    "content": "# Release Service\n#### service breakdown\n---"
   }
  },
  {
   "title": "Total releases",
   "type": "stat",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(release_reason) (release_total{target=~\"$tenant\", source_cluster=~\"$cluster\"})",
     "legendFormat": "{{release_reason}}"
    },
    {
     "expr": "sum (label_replace( sum by (namespace) (release_total{validation_reason=\"Failed\", source_cluster=~\"$cluster\"}  OR vector(0)), \"release_reason\", \"Invalid\", \"\",\"\")) by (release_reason)",
     "legendFormat": "{{release_reason}}"
    },
    {
     "expr": "label_replace( sum by (namespace) (release_concurrent_total{source_cluster=~\"$cluster\"}), \"release_reason\", \"Concurrent\", \"\", \"\")",
     "legendFormat": "{{release_reason}}"
    },
    {
     "expr": "label_replace( (sum by (namespace) (release_total{release_reason=\"Succeeded\", target=~\"$tenant\", source_cluster=~\"$cluster\"}) / sum by (namespace) (release_total)) , \"release_reason\", \"Succeeded %\", \"\",\"\")",
     "legendFormat": "{{release_reason}}"
    },
    {
     "expr": "label_replace( (sum by (namespace) (release_total{release_reason=\"Failed\", target=~\"$tenant\", source_cluster=~\"$cluster\"}) / sum by (namespace) (release_total)) , \"release_reason\", \"Failed %\", \"\",\"\")",
     "legendFormat": "{{release_reason}}"
    }
   ]
  },
  {
   "title": "pipelineruns duration (95% quantile)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 9, "x": 9, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (pipeline, le) (rate(tekton_pipelines_controller_pipelinerun_duration_seconds_bucket{namespace=\"rhtap-releng-tenant\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 18, "x": 0, "y": 9 }, "options": { "content": "#### release duration\n---" } },
  {
   "title": "time to succeed",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum by (namespace, release_reason, le) (release_duration_seconds_bucket{release_reason=\"Succeeded\"})",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "release duration heatmap",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 9, "x": 9, "y": 11 },
   "targets": [
    {
     "expr": "sum by(namespace, le) (release_duration_seconds_bucket) > 0",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "time to fail",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum by(namespace, release_reason, le) (release_duration_seconds_bucket{release_reason=\"Failed\"})",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 3, "w": 18, "x": 0, "y": 21 }, "options": { "content": "---\n#### service breakdown" } },
  {
   "title": "releases processing count over time",
   "type": "timeseries",
   "description": "Show the accumulated amount of releases over time. These numbers are reset when the controller is restarted",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum by (release_reason) (release_total{release_reason=~\"Failed|Succeeded\"})",
     "legendFormat": "{{release_reason}}"
    }
   ]
  },
  {
   "title": "releases 95% duration quantile over time",
   "type": "timeseries",
   "description": "The release duration quantile, show the 0.95 quantile of a release duration.\n\nhttps://en.wikipedia.org/wiki/Quantile",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (release_reason, le) (rate(release_duration_seconds_bucket{release_reason=~\"Failed|Succeeded\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "slowest releases (99% quantile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (target, le) (rate(release_duration_seconds_bucket{release_reason=~\"Failed|Succeeded\"}[$__rate_interval])) > 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "releases failures",
   "type": "timeseries",
   "description": "Show the accumulated amount of releases over time. These numbers are reset when the controller is restarted",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "label_replace(\n    (sum (release_total{release_reason=~\"Failed\"}) by (namespace) ) / ( sum(release_total) by (namespace) ),\n\"label\", \"Failed\",  \"\", \"\")",
     "legendFormat": "{{label}}"
    }
   ]
  },
  {
   "title": "releases failure rate",
   "type": "timeseries",
   "description": "Show the release failure rate over time.",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(release_total{release_reason=\"Failed\"}[$__rate_interval])) by(release_reason)",
     "legendFormat": "{{label}}"
    }
   ]
  },
  {
   "title": "Taskrun durations",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(pipeline, task, le) (rate(tekton_pipelines_controller_pipelinerun_taskrun_duration_seconds_bucket{namespace=\"rhtap-releng-tenant\"}[$__interval]))) >= 0",
     "legendFormat": "{{pipeline}}/{{task}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 18, "x": 0, "y": 50 },
   "options": {
    "content": "---\n### release operator\n---\n##### container info"
   }
  },
  {
   "title": "manager memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"release-service\", container=\"manager\"}) by(container)",
     "legendFormat": "used"
    },
    {
     "expr": "max(kube_pod_container_resource_limits{namespace=\"release-service\", container=\"manager\", resource=\"memory\"}) by(container)",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "manager cpu usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{namespace=\"release-service\", container=\"manager\"}[$__interval])) by (container)",
     "legendFormat": "used"
    },
    {
     "expr": "max(kube_pod_container_resource_limits{namespace=\"release-service\", container=\"manager\", resource=\"cpu\"}) by(container)",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "manager container status change timeline",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 54 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_terminated_reason{container=\"manager\", namespace=\"release-service\"} > 0) by (reason)\nOR\nsum(kube_pod_container_status_waiting_reason{container=\"manager\", namespace=\"release-service\"} > 0) by (reason)\nOR\nsum(kube_pod_container_status_last_terminated_reason{container=\"manager\", namespace=\"release-service\"} > 0) by (reason)\nOR\nlabel_replace(sum(sum(kube_pod_container_status_ready{namespace=\"release-service\", container=\"manager\"} > 0) by(container)) without(container), \"reason\", \"Ready\", \"\", \"\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "manager status changes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 62 },
   "targets": [
    {
     "expr": "sum(changes(kube_pod_container_status_ready {container=\"manager\", namespace=\"release-service\"}[10m])) by (container)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total number of reconciles by type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 62 },
   "targets": [
    {
     "expr": "sum by (result) (controller_runtime_reconcile_total{controller=\"release\", namespace=\"release-service\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Workqueue retries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 62 },
   "targets": [
    {
     "expr": "label_replace(sum(workqueue_retries_total{name=\"release\"}),\"label\", \"absolute\", \"\", \"\")",
     "legendFormat": "{{label}}"
    },
    {
     "expr": "label_replace(sum(increase(workqueue_retries_total{name=\"release\"}[$__rate_interval])), \"label\", \"increase rate\", \"\", \"\")",
     "legendFormat": "{{label}}"
    }
   ]
  }
 ]
}