apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleaseStrategy
metadata:
  name: m5-strategy
  namespace: managed
spec:
  pipeline: m5-release-pipeline
#  bundle: quay.io/hacbs-release/demo:m5-alpine
  policy: m5-policy
  params:
    - name: extraConfigGitUrl
      value: https://github.com/davidmogar/strategy-configs.git
    - name: extraConfigPath
      value: m5.yaml
    - name: extraConfigRevision # optional field, default is main
      value: main
  serviceAccount: m5-service-account
