apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleaseLink
metadata:
  name: m5-release-link-demo
  namespace: demo
spec:
  displayName: Users's ReleaseLink
  application: m5-app
  target: managed
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleaseLink
metadata:
  name: m5-release-link-managed
  namespace: managed
spec:
  displayName: Managed Workspace's ReleaseLink
  application: m5-app
  target: demo
  releaseStrategy: m5-strategy
