---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: release-service-on-push
  annotations:
    pipelinesascode.tekton.dev/on-event: "[push]" 
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
    pipelinesascode.tekton.dev/max-keep-runs: "5"
spec:
  params:
    - name: git-url
      value: "{{ repo_url }}"
    - name: revision
      value: "{{ revision }}"
    - name: output-image
      value: 'quay.io/redhat-appstudio/release-service:{{ revision }}'
    - name: path-context
      value: .
    - name: dockerfile
      value: Dockerfile
    - name: infra-deployment-update-script
      value: |
        sed -i -e 's|\(https://github.com/redhat-appstudio/release-service/config/default?ref=\)\(.*\)|\1{{ revision }}|' -e 's/\(newTag: \).*/\1{{ revision }}/' components/release/kustomization.yaml
  pipelineRef:
    name: docker-build
    bundle: quay.io/redhat-appstudio/hacbs-core-service-templates-bundle:latest
  workspaces: 
   - name: workspace 
     persistentVolumeClaim: 
        claimName: app-studio-default-workspace 
     subPath: release-service-push-{{ revision }}
   - name: deploy-key
     secret:
        secretName: infra-deployments-deploy-key
