---
name: Go Test on Pull Requests
on:  # yamllint disable-line rule:truthy
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - '**.go'
  workflow_dispatch:
  merge_group:
    types: [checks_requested]
jobs:
  gosec:
    name: Check GO security
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 1
          ref: ${{ github.sha }}
      - name: Run Gosec Security Scanner
        id: gosec
        uses: securego/gosec@6351b0c6fcc7d75acb230a9be7f9047aada322ae # master
        with:
          args: -exclude-generated ./...
        env:
          GOROOT: ""
        continue-on-error: true
      - name: Run Gosec Security Scanner - save SARIF
        id: gosec-sarif
        uses: securego/gosec@6351b0c6fcc7d75acb230a9be7f9047aada322ae # master
        with:
          # we let the report trigger a failure using the GitHub Security features.
          args: -exclude-generated -fmt sarif -out results.sarif ./...
        env:
          GOROOT: ""
        continue-on-error: true
      - name: Upload SARIF file
        if: github.event_name != 'merge_group'
        uses: github/codeql-action/upload-sarif@7211b7c8077ea37d8641b6271f6a365a22a5fbfa # v4.36.0
        with:
          sarif_file: results.sarif
      - name: Check gosec result
        run: |
          if [ "${{ steps.gosec-sarif.outcome }}" != "success" ]
          then
            echo "Gosec failed. The errors and warnings should be displayed in the PR."
            exit 1
          fi
