---
name: Govulncheck on Pull Requests
on:
  pull_request:
  workflow_dispatch:
jobs:
  govulncheck:
    name: Scan for Vulnerabilities in Code
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set up Go 1.x
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.3
      - run: go version
      - name: Run govulncheck
        run: |
          go install golang.org/x/vuln/cmd/govulncheck@latest
          govulncheck ./...
